events {}

http {
  gzip on;
  gzip_types text/plain application/json application/javascript text/css text/xml application/xml+rss application/atom+xml image/svg+xml;

  # Redirect HTTP to HTTPS
  server {
    listen 80;
    server_name localhost;

    return 301 https://$host$request_uri;
  }

  # Main HTTPS Server
  server {
    listen 8081 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/certs/cert.crt;
    ssl_certificate_key /etc/nginx/certs/cert.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
      auth_basic "Restricted Access";
      auth_basic_user_file /etc/nginx/htpasswd;

      proxy_pass http://supabase-studio:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
